#pragma pack_matrix (column_major) // sets default order to column major

struct input
{
float3 position 	: POSITION;
};


struct output
{
float4 position : TEXCOORD0;
float4 gl_Position : POSITION;
float2 texCoords 	: TEXCOORD1;
};

output main(input IN, uniform float2 viewport)
{
output OUT;
OUT.texCoords = (IN.position.xy + 1.0) / 2.0;
OUT.position = float4(IN.position, 1.0);
OUT.gl_Position = OUT.position * float4(1,1,0,1);
return OUT;
}